In [6]:
from sklearn.neighbors import LocalOutlierFactor as lof
import numpy as np
import pandas as pd
x = [1.0]*30
x.append(10)

# Cast to a data frame
X = pd.DataFrame(x)

# Fit the local outlier factor and print the outlier scores
print(lof().fit_predict(X))

[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1 -1]


In [ ]:
X = list([1.0]*30)

# Create an instance of a lof novelty detector
detector = lof(novelty=True)

# Fit the detector to the data
detector.fit(X)

print

In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 400
df = pd.read_csv('arrh.csv')
df.head()

age  sex  height  weight  QRSduration  PRinterval  Q-Tinterval  Tinterval  \
0   75    0     190      80           91         193          371        174   
1   56    1     165      64           81         174          401        149   
2   54    0     172      95          138         163          386        185   
3   55    0     175      94          100         202          380        179   
4   75    0     190      80           88         181          360        177   

   Pinterval  QRS  ...  chV6_QwaveAmp  chV6_RwaveAmp  chV6_SwaveAmp  \
0        121  -16  ...            0.0            9.0           -0.9   
1         39   25  ...            0.0            8.5            0.0   
2        102   96  ...            0.0            9.5           -2.4   
3        143   28  ...            0.0           12.2           -2.2   
4        103  -16  ...            0.0           13.1           -3.6   

   chV6_RPwaveAmp  chV6_SPwaveAmp  chV6_PwaveAmp  chV6_TwaveAmp  chV6_QRSA  \
0             0.0             0.0            0.9            2.9       23.3   
1             0.0             0.0            0.2            2.1       20.4   
2             0.0             0.0            0.3            3.4       12.3   
3             0.0             0.0            0.4            2.6       34.6   
4             0.0             0.0           -0.1            3.9       25.4   

   chV6_QRSTA  class  
0        49.4      0  
1        38.8      0  
2        49.0      0  
3        61.6      1  
4        62.8      0  

[5 rows x 280 columns]

In [45]:
round_truth = np.array([-1., -1., -1.,  1., -1., -1.,  1.,  1.,  1., -1., -1.,  1., -1.,
       -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,
       -1., -1., -1., -1., -1.,  1.,  1.,  1., -1.,  1.,  1., -1.,  1.,
       -1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1.,
       -1., -1., -1., -1.,  1.,  1., -1.,  1., -1., -1.,  1.,  1.,  1.,
        1., -1.,  1., -1.,  1., -1., -1.,  1.,  1.,  1., -1., -1., -1.,
        1.,  1.,  1.,  1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,
       -1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,
       -1., -1., -1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1., -1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
        1.,  1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,
        1., -1., -1., -1.,  1.,  1., -1.,  1.,  1.,  1., -1., -1.,  1.,
        1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,
       -1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1.,  1., -1.,  1., -1.,
        1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1., -1., -1.,  1.,
        1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1., -1.,
        1., -1., -1.,  1., -1., -1., -1.,  1., -1., -1., -1., -1.,  1.,
        1., -1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,
        1., -1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1.,
        1., -1.,  1., -1., -1., -1., -1.,  1.,  1., -1., -1., -1., -1.,
        1., -1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,
        1.,  1., -1.,  1., -1., -1.,  1.,  1.,  1.,  1., -1., -1., -1.,
        1.,  1.,  1.,  1.,  1., -1.,  1., -1., -1., -1., -1., -1., -1.,
        1., -1.,  1., -1., -1., -1.,  1., -1., -1., -1., -1.,  1.,  1.,
       -1., -1.,  1.,  1., -1.,  1.,  1., -1., -1.,  1., -1., -1., -1.,
        1., -1., -1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1.,
        1.,  1., -1., -1.,  1., -1., -1.,  1., -1.,  1., -1.,  1.,  1.,
       -1.,  1., -1., -1.,  1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1.,  1., -1., -1., -1.,  1., -1.,  1., -1.,  1., -1., -1., -1.,
        1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1., -1., -1.,  1.,
        1.,  1.,  1.,  1.,  1., -1.,  1., -1., -1.,  1., -1., -1.,  1.,
       -1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,  1.,  1.,  1.,
        1., -1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1., -1.,  1.,
       -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1.,  1.])

In [68]:
from sklearn.metrics import confusion_matrix
preds = lof().fit_predict(X)
X = df.drop('class', axis=1)
y = df[['class']]
X.shape

(452, 279)

In [69]:
# Print the confusion matrix
print(confusion_matrix(ground_truth, preds))

[[ 31 176]
 [  2 243]]


In [70]:
preds = lof(contamination=0.2).fit_predict(X)
print(confusion_matrix(ground_truth, preds))


[[ 72 135]
 [ 19 226]]


In [71]:
mean = np.mean(ground_truth==-1.0)
mean

0.4579646017699115

In [72]:
preds = lof(contamination=mean.round(2)).fit_predict(X)

# Print the confusion matrix
print(confusion_matrix(ground_truth, preds))

[[142  65]
 [ 66 179]]


In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [74]:
# Import the novelty detector
from sklearn.svm import OneClassSVM as onesvm

# Fit it to the training data and score the test data
svm_detector = onesvm().fit(X_train)
scores = svm_detector.score_samples(X_test)
scores

array([126.63983442, 131.13609448, 132.37166221, 127.49031836,
       123.54796749,  76.78544685, 134.90034264, 127.80646544,
       126.96556404, 134.50157218, 130.55072545, 127.4883711 ,
       133.0817829 , 130.04423535, 125.36645872, 115.85795581,
       133.23112849, 132.00226059, 129.94593563, 125.28772774,
       133.85578664, 131.97679399, 134.99683258, 132.46050854,
       127.90345572, 131.12013022, 136.22532048, 127.52972711,
       129.93580602, 131.33803916, 129.15046285, 125.04635676,
       128.85115441, 132.17797397, 114.93818228, 130.11475748,
       134.61311502, 130.4351704 , 135.23997729, 135.04499415,
       112.66802884, 135.6662616 , 133.70304022, 116.29433613,
       129.31827984, 130.76379401, 130.97200745, 130.35662325,
       113.48073188, 104.51739455, 131.0370543 , 132.64655627,
       134.05185209, 135.86902528, 135.63769595, 104.82315149,
       134.87504156, 134.86756449, 131.65431011, 129.68194577,
       129.09261644, 135.14905506, 134.92691442, 126.51

In [82]:
# Import the novelty detector
from sklearn.ensemble import IsolationForest as isof

# Fit it to the training data and score the test data
isof_detector = isof().fit(X_train)
scores = isof_detector.score_samples(X_test)

In [81]:
# Import the novelty detector
from sklearn.neighbors import LocalOutlierFactor as lof

# Fit it to the training data and score the test data
lof_detector = lof(novelty=True).fit(X_train)
scores = lof_detector.score_samples(X_test)

In [80]:
# Fit a one-class SVM detector and score the test data
nov_det = onesvm().fit(X_train)
scores = nov_det.score_samples(X_test)

In [78]:
# Find the observed proportion of outliers in the test data
prop = np.mean(y_test==1.0)

# Compute the appropriate threshold
threshold = np.quantile(scores, prop)

# Print the confusion matrix for the thresholded scores
print(confusion_matrix(y_test, (scores > threshold)))

[[33 21]
 [26 33]]


In [140]:
proteins = pd.read_csv('proteins_exercises.csv')

In [141]:
proteins.head()

label                                                seq
0  IMMUNE SYSTEM  LTKCQEEVSHIPAVHPGSFRPKCDENGNYLPLQCYGSIGYCWCVFP...
1  IMMUNE SYSTEM  GPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGV...
2  IMMUNE SYSTEM                 FNMQCQRRFYEALHDPNLNEEQRNAKIKSIRDDC
3  IMMUNE SYSTEM  EVQLVESGGGLVQPGGSLRLSCAASGFTFTDYTMDWVRQAPGKGLE...
4  IMMUNE SYSTEM  DIQMTQSPSSLSASVGDRVTITCKASQDVSIGVAWYQQKPGKAPKL...

In [142]:
proteins['seq'].iloc[:3].values

array(['LTKCQEEVSHIPAVHPGSFRPKCDENGNYLPLQCYGSIGYCWCVFPNGTEVPNTRSRGHHNCSES',
       'GPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSL',
       'FNMQCQRRFYEALHDPNLNEEQRNAKIKSIRDDC'], dtype=object)

In [143]:
sequences = np.array(proteins['seq'].iloc[:3].values.reshape(-1,1))

In [144]:
from scipy.spatial.distance import pdist, squareform
import stringdist

In [ ]:
# Wrap the RD-Levenshtein metric in a custom function
def my_rdlevenshtein(u, v):
    return stringdist.rdlevenshtein(u[0], v[0])

# Reshape the array into a numpy matrix
sequences = np.array(proteins['seq']).reshape(-1, 1)

# Compute the pairwise distance matrix in square form
M = squareform(pdist(sequences, my_rdlevenshtein))

In [138]:
from sklearn.metrics import accuracy_score, roc_auc_score
# Run a LoF algorithm on the precomputed distance matrix
preds = lof(metric='precomputed').fit_predict(M)

# Compute the accuracy of the outlier predictions
print(accuracy_score(proteins['label'] == 'VIRUS', preds == -1))

TypeError: 'numpy.ndarray' object is not callable

In [132]:
proteins['len'] = proteins['seq'].apply(lambda s: len(s))

In [133]:
from sklearn.preprocessing import LabelEncoder
proteins['first'] = LabelEncoder().fit_transform(proteins['seq'].apply(lambda s: list(s)[0]))

In [134]:
proteins.head()

label                                                seq  len  \
0  IMMUNE SYSTEM  LTKCQEEVSHIPAVHPGSFRPKCDENGNYLPLQCYGSIGYCWCVFP...   65   
1  IMMUNE SYSTEM  GPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGV...  207   
2  IMMUNE SYSTEM                 FNMQCQRRFYEALHDPNLNEEQRNAKIKSIRDDC   34   
3  IMMUNE SYSTEM  EVQLVESGGGLVQPGGSLRLSCAASGFTFTDYTMDWVRQAPGKGLE...  222   
4  IMMUNE SYSTEM  DIQMTQSPSSLSASVGDRVTITCKASQDVSIGVAWYQQKPGKAPKL...  214   

   first  
0      8  
1      4  
2      3  
3      2  
4      1

In [135]:
len(proteins)

100

In [139]:
#scores_lof = lof_detector.negative_outlier_factor_
scores_lof = preds.negative_outlier_factor_
scores_lof

AttributeError: 'numpy.ndarray' object has no attribute 'negative_outlier_factor_'

In [130]:
len(scores_lof)

339

In [121]:
true_y = (proteins['label']=='IMMUNE SYSTEM').values

In [123]:
print(roc_auc_score(true_y, scores_lof))

ValueError: Found input variables with inconsistent numbers of samples: [100, 339]

ValueError: Found input variables with inconsistent numbers of samples: [100, 339]